/*CRIAÇÃO DO BANCO DE DADOS DO API DE HOSPITAIS.
    A IDEIA É QUE O HOSPITAL INFORMA VIA API A SITUAÇÃO DE SEUS LEITOS E PACIENTES.
    O DATABASE DB_HOSPITAL FOI CRIADO DIRETO NO PGADMIN DO POSTGRESQL. 

    CREATE DATABASE DB_HOSPITAL;
*/

/*CRIAÇÃO DAS TABELAS DO BANCO DE DADOS DE HOSPITAL*/
CREATE TABLE HOSPITAL(
    PK_HOSTPITAL SERIAL PRIMARY KEY,
    NOME_SOCIAL VARCHAR(100) NOT NULL,
    NOME_FANTASIA VARCHAR(100),
    CNPJ VARCHAR(22) NOT NULL,
    INS_ESTADUAL VARCHAR(20) NOT NULL,
    NUM_LEITOS INT, 
    NUM_UTI INT,
    LOTACAO_ATUAL FLOAT   
);

CREATE TABLE GUIA_ATENDIMENTO(
    PK_GUIA_ATENDIMENTO SERIAL PRIMARY KEY, 
    HORARIO_CHEGADA timestamp(6) NOT NULL,
    CLASSIFICACAO VARCHAR(10) NOT NULL, /*adicionar constraint posteriormente*/

    FK_HOSPITAL INTEGER, 
    FK_FUNCIONARIO INTEGER,
    FK_PACIENTE INTEGER
);



CREATE TABLE FUNCIONARIO(
    PK_FUNCIONARIO SERIAL PRIMARY KEY,
    NOME_FUNCIONARIO VARCHAR(100) NOT NULL, 
    CPF VARCHAR(14) NOT NULL, 
    RG VARCHAR(14) NOT NULL, 
    HORARIO VARCHAR(20), 
    ESPECIALIDADE VARCHAR(50), /*ALTERAR PARA TABELA POSTERIOREMTNE*/
    DATA_NASCIMENTO timestamp(6)
);

CREATE TABLE PACIENTE(
    PK_PACIENTE SERIAL PRIMARY KEY,
    NOME_PACIENTE VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) NOT NULL, 
    RG VARCHAR(14) NOT NULL,
    DATA_NASCIMENTO timestamp(6)
);

CREATE TABLE CONTATO(
    PK_CONTATO SERIAL PRIMARY KEY,
    TELEFONE VARCHAR(20),
    CELULAR VARCHAR(20),
    EMAIL VARCHAR(100), 
    CELULAR_EMERGENCIA VARCHAR(20),

    FK_PACIENTE INTEGER, 
    FK_FUNCIONARIO INTEGER
);

CREATE TABLE ENDERECO(
    PK_ENDERECO SERIAL PRIMARY KEY, 
    CIDADE VARCHAR(30) NOT NULL, 
    BAIRRO VARCHAR(50) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL, 
    NUMERO INT, 
    
    FK_PACIENTE INTEGER, 
    FK_FUNCIONARIO INTEGER
);


/*ADICIONANDO CONSTRAINS AS TABELAS CRIADAS*/

/*GUIA ATENDIMENTO*/
    ALTER TABLE GUIA_ATENDIMENTO 
    ADD CONSTRAINT CONST_GUIA_ATENDIMENTO_HOSPITAL
    FOREIGN KEY (FK_HOSPITAL) 
    REFERENCES HOSPITAL (PK_HOSTPITAL);

    ALTER TABLE GUIA_ATENDIMENTO 
    ADD CONSTRAINT CONST_GUIA_ATENDIMENTO_FUNCIONARIO 
    FOREIGN KEY (FK_FUNCIONARIO) 
    REFERENCES FUNCIONARIO (PK_FUNCIONARIO);

    ALTER TABLE GUIA_ATENDIMENTO 
    ADD CONSTRAINT CONST_GUIA_ATENDIMENTO_PACIENTE
    FOREIGN KEY (FK_PACIENTE) 
    REFERENCES PACIENTE (PK_PACIENTE);

/*ENDERECO*/
    ALTER TABLE ENDERECO 
    ADD CONSTRAINT CONST_ENDERECO_FUNCIONARIO 
    FOREIGN KEY (FK_FUNCIONARIO) 
    REFERENCES FUNCIONARIO (PK_FUNCIONARIO);

    ALTER TABLE ENDERECO 
    ADD CONSTRAINT CONST_ENDERECO_PACIENTE 
    FOREIGN KEY (FK_PACIENTE) 
    REFERENCES PACIENTE (PK_PACIENTE);

/*CONTATO*/
    ALTER TABLE CONTATO 
    ADD CONSTRAINT CONST_CONTATO_FUNCIONARIO 
    FOREIGN KEY (FK_FUNCIONARIO) 
    REFERENCES FUNCIONARIO (PK_FUNCIONARIO);

    ALTER TABLE ENDERECO 
    ADD CONSTRAINT CONST_CONTATO_PACIENTE 
    FOREIGN KEY (FK_PACIENTE) 
    REFERENCES PACIENTE (PK_PACIENTE);